services:
  backend:
    image: eclipse-temurin:21
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: "./mvnw spring-boot:run"

  frontend:
    image: nginx:latest
    depends_on:
      - backend
    volumes:
      - ./build:/usr/share/nginx/html
    ports:
      - 80:80
